### ISSUE TITLE
use get_measure_dependencies() for a report that contains a connection to Microsoft Analysis Services Tabular model

### ISSUE THREAD

**Issue by KoenLoeffen** [microsoft/semantic-link-labs#301]
I have a report called "Work in Progress" that uses a semantic model based on a Microsoft Analysis Services Tabular model. When using the get_measure_dependencies(report="Work in Progress", workspace="test") function for this report is returns the following error:

`AdomdErrorResponseException: Either the database '<oii>Work in Progress</oii>' does not exist, or you do not have permissions to access it.

Technical Details:
Date (UTC): 11/25/2024 4:17:54 PM
   at Microsoft.AnalysisServices.AdomdClient.XmlaClient.CheckForSoapFault(XmlReader reader, XmlaResult xmlaResult, Boolean throwIfError)
   at Microsoft.AnalysisServices.AdomdClient.XmlaClient.CheckForError(XmlReader reader, XmlaResult xmlaResult, Boolean throwIfError)
   at Microsoft.AnalysisServices.AdomdClient.XmlaClient.CreateSession(ListDictionary properties, Boolean sendNamespaceCompatibility, String sessionToken)
   at Microsoft.AnalysisServices.AdomdClient.XmlaClient.CreateSession(ListDictionary properties, Boolean sendNamespaceCompatibility)
   at Microsoft.AnalysisServices.AdomdClient.AdomdConnection.XmlaClientProvider.Microsoft.AnalysisServices.AdomdClient.AdomdConnection.IXmlaClientProviderEx.CreateSession(Boolean sendNamespaceCompatibility)
   at Microsoft.AnalysisServices.AdomdClient.AdomdConnection.ConnectToXMLA(Boolean createSession, Boolean isHTTP)
   at Microsoft.AnalysisServices.AdomdClient.AdomdConnection.Open()`

I know this semantic model exists in the workspace I use within the function and this function does work for semantic models that have a different data connection. Only with the Analysis services connection it goes wrong. I am also an admin in the Tabular model. Could you please help me out?

**Comment by m-kovalsky** [comment]
Firstly, this function doesn't have a parameter called 'report'. It's called 'dataset'. Second, make sure everything is spelled correctly.

Third, can you run this?


```python
import sempy.fabric as fabric
fabric.evaluate_dax(dataset="Work in Progress", workspace="test", dax_string = """ SELECT * FROM $SYSTEM.DISCOVER_CALC_DEPENDENCY"""
```

**Comment by KoenLoeffen** [comment]
Thanks for your response. Indeed the parameter is dataset. However, I am not able to run the code you shared. It returns the same issue. However, I do have a 'Work in Progress' semantic model within the workspace. I just found out that the semantic model doesn't pop up when I run fabric.list_datasets(workspace="test"). Although, other semantic models do pop up, but those aren't connected to a Analysis Services source. Maybe that is the problem?

**Comment by m-kovalsky** [comment]
Please check that the following tenant setting is disabled

![Image](https://github.com/user-attachments/assets/b88f8475-8fe5-43de-b32f-d9216613b08e)

**Comment by KoenLoeffen** [comment]
That's indeed disabled.

**Comment by m-kovalsky** [comment]
What are your permissions on the workspace in which the semantic model resides?

**Comment by m-kovalsky** [comment]
This function (and really all functions) only work with semantic models which are published to the service. You have a report in the service but the model is not so this and other functions will not work against the model. It will only work if you publish the model to the service and run the function against that model.
